import Header from "./Header";
import Footer from "./Footer";
import CartMenu from "./CartMenu";
import Head from "next/head";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>KICKS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/af1.png" />
      </Head>
      <Header />
      <main>{children}</main>
      <CartMenu />
      <Footer />
    </>
  );
};

export default Layout;
